### ISSUE TITLE
Provided weights do not control the system correctly

### ISSUE THREAD

**Issue by zoythum** [Han-Adam/GeneralAnalyze#1]
I have a question regarding the provided weights because I am not able to reproduce the results of figure 7b and 7d where the controller is capable of reducing the error between the position and the setpoint to zero.
I modified the environment to obtain information on the state instead of the error because I want to plot the position directly 

```python
def info(self):
  return {'pos': self.pos, 'target': self.target}
```

Then I am executing the following code 

```python
agent = DDPG(path, s_dim=2, gamma=gamma)
        agent.load_net(...)  # here I slightly modified the load function but it loads the latest network of the latest episode
        env = Env()

        obs = env.reset()
        info = env.info()
        states = [info['pos']]
        target = info['target']
        actions = []

        for _ in range(300):
            a = agent.get_action(obs)
            actions.append(a[0])
            s_, r = env.step(a[0])
            states.append(env.info()['pos'])

        plt.figure()
        plt.plot(states, color='green', label='Env output')
        plt.plot(actions, color='red', label='Actions')
        plt.hlines(target, xmin=0, xmax=300, label='Setpoint')
        plt.legend()
        plt.show()
```
If I understand correctly the output of the environment should start from a random point between -5 and 5 and then move to 0 due to the control action of the agent. Unfortunately the result diverges and the output of the environment goes to infinity as you can see from [this image](https://github.com/Han-Adam/GeneralAnalyze/files/14771838/divergence.pdf).

I am wondering if I am doing something wrong in my code or if the weights provided are not the ones used in the paper. 
Thank you for the support

**Comment by Han-Adam** [comment]
Thanks for your attention on our work and questions.


Your code is 
agent=DDPG(path, s_dim=2, gamma=gamma)
agent.load_net(...)  # here I slightly modified the load function but it loads the latest network of the latest episode

However, the oriainal agent has "var" adding noise to the action, and this is only used for training process.
During testing process, please add "agent.var = 0" after initializing your agent.
















At 2024-03-27 18:33:12, "Alessandro Nazzari" ***@***.***> wrote:

I have a question regarding the provided weights because I am not able to reproduce the results of figure 7b and 7d where the controller is capable of reducing the error between the position and the setpoint to zero.
I modified the environment to obtain information on the state instead of the error because I want to plot the position directly

definfo(self):
  return {'pos': self.pos, 'target': self.target}

Then I am executing the following code

agent=DDPG(path, s_dim=2, gamma=gamma)
        agent.load_net(...)  # here I slightly modified the load function but it loads the latest network of the latest episodeenv=Env()

        obs=env.reset()
        info=env.info()
        states= [info['pos']]
        target=info['target']
        actions= []

        for_inrange(300):
            a=agent.get_action(obs)
            actions.append(a[0])
            s_, r=env.step(a[0])
            states.append(env.info()['pos'])

        plt.figure()
        plt.plot(states, color='green', label='Env output')
        plt.plot(actions, color='red', label='Actions')
        plt.hlines(target, xmin=0, xmax=300, label='Setpoint')
        plt.legend()
        plt.show()

If I understand correctly the output of the environment should start from a random point between -5 and 5 and then move to 0 due to the control action of the agent. Unfortunately the result diverges and the output of the environment goes to infinity as you can see from this image.

I am wondering if I am doing something wrong in my code or if the weights provided are not the ones used in the paper.
Thank you for the support

**Comment by zoythum** [comment]
Thanks for the super quick reply! 
I tried setting the variance to zero and now the actions are fixed to a single value but the environment is [still diverging](https://github.com/Han-Adam/GeneralAnalyze/files/14772184/novar.pdf)

**Comment by Han-Adam** [comment]
please send your whole code in zip to me



---- Replied Message ----
| From | Alessandro ***@***.***> |
| Date | 03/27/2024 18:55 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Han-Adam/GeneralAnalyze] Provided weights do not control the system correctly (Issue #1) |

Thanks for the super quick reply!
I tried setting the variance to zero and now the actions are fixed to a single value but the environment is still diverging

**Comment by Han-Adam** [comment]
Another possible problem. Do not use ReLU function, ReLU 180 is shown as in Fig. 11 (b), it is used to demonstrate the failure network.



Instead, use networks in Tanh package.










At 2024-03-27 18:55:24, "Alessandro Nazzari" ***@***.***> wrote:

Thanks for the super quick reply!
I tried setting the variance to zero and now the actions are fixed to a single value but the environment is still diverging

**Comment by zoythum** [comment]
Yes I am using the tanh model. I have sent you the code

**Comment by Han-Adam** [comment]
Add "obs = s_" after "s_, r = env.step(a[0])". The observation sent to agent has never been changed in your original code.













At 2024-03-27 19:12:43, "Alessandro Nazzari" ***@***.***> wrote:

Yes I am using the tanh model. I have sent you the code

**Comment by zoythum** [comment]
It was, indeed, a trivial error on my part. Thank you very much for the support!
